name: manually-release 
on: workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Linux glibc image
        run: docker build .

      - name: Compile executable on Linux glibc
        run: |
          mkdir -p build
          docker run \
            -v ./build:/root/scheme-langserver/build/ \
            $(docker build -q .) \
            bash -c 'source .akku/bin/activate
                     compile-chez-program run.ss --static
                     mv run build/scheme-langserver-x86_64-linux-glibc || exit 1
                     '

      - name: generate tag
        id: tag
        run: echo "tag_name=auto-build-$(date -u +%Y-%m-%d-%H-%M-%S)" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          files: build/scheme-langserver-x86_64-linux-glibc
