name: Release 
on:
  push:
  workflow_dispatch:
  # pull_request:
  #   branches: main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Linux glibc image
        run: docker build .

      # - name: Build Linux musl image
      #   run: docker build -f Dockerfile.musl .

      - name: Compile executable on Linux glibc
        run: |
          mkdir -p build
          docker run \
            -v ./build:/root/scheme-langserver/build/ \
            $(docker build -q .) \
            bash -c 'source .akku/bin/activate
                     compile-chez-program run.ss --static
                     mv run build/scheme-langserver-x86_64-linux-glibc || exit 1
                     '

      # - name: Compile executable on Linux musl
      #   run: |
      #     mkdir -p build
      #     docker run \
      #       -v ./build:/root/scheme-langserver/build/ \
      #       $(docker build -f Dockerfile.musl -q .) \
      #       ash -c 'source .akku/bin/activate
      #               compile-chez-program run.ss --static
      #               mv run build/scheme-langserver-x86_64-linux-musl || exit 1
      #               '

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          md5=$(md5sum build/scheme-langserver-x86_64-linux-glibc | awk '{print $1}')
          sha256=$(sha256sum build/scheme-langserver-x86_64-linux-glibc | awk '{print $1}')
          note="### build time

          $(date -uIs)
          
          ### File Hashes
          
          | Algorithm | Hash |
          |-----------|------|
          | MD5       | \`$md5\` |
          | SHA256    | \`$sha256\` |"

          gh release edit auto-build --title auto-build-$(date +%Y-%m-%d) --notes "$note" -R ${{ github.repository }}

          gh release upload auto-build build/scheme-langserver-x86_64-linux-glibc --clobber -R ${{ github.repository }}